application: pyramid-gae-tutorial
version: 0-0-1
runtime: python
api_version: 1

default_expiration: "4d 5h"

derived_file_type:
- python_precompiled

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*/tests/.*
- ^modeling/.*
- ^sample_data/.*
- ^(.*/)?.*/.svn/.*


error_handlers:
  - file: default_error.html

handlers:


- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: "30d"


- url: /static
  static_dir: static
  expiration: "30d"



- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin


- url: .*
  script: main.py
  

